import type { TCatalogData } from "../interfaces"

export const CATALOG_MOCK: TCatalogData = {
  categories: [
    { id: "all", label: "Todos", count: 150, isActive: true },
    { id: "alimentos", label: "Alimentos", count: 45 },
    { id: "bebidas", label: "Bebidas", count: 28 },
    { id: "lacteos", label: "Lacteos", count: 18 },
    { id: "limpieza", label: "Limpieza", count: 32 },
    { id: "cuidado-personal", label: "Cuidado Personal", count: 27 },
  ],
  products: [
    {
      id: "aceite-vegetal-1l",
      name: "Aceite Vegetal Premium 1L",
      brand: "Oleica",
      category: "Alimentos",
      rating: 4.5,
      reviews: 128,
      price: 8500,
      oldPrice: 9500,
      unitLabel: "por unidad",
      minOrderLabel: "Min: 6 unidades",
      stock: 150,
      badges: [
        { label: "-10%", tone: "sale" },
        { label: "Top ventas", tone: "hot" },
      ],
    },
    {
      id: "arroz-grano-largo-5kg",
      name: "Arroz Premium Grano Largo 5kg",
      brand: "Arrocera Nacional",
      category: "Alimentos",
      rating: 4.8,
      reviews: 256,
      price: 22000,
      unitLabel: "por bulto",
      minOrderLabel: "Min: 4 bultos",
      stock: 85,
      badges: [{ label: "Nuevo", tone: "new" }],
    },
    {
      id: "detergente-liquido-3l",
      name: "Detergente Liquido 3L",
      brand: "LimpiMax",
      category: "Limpieza",
      rating: 4.3,
      reviews: 89,
      price: 15000,
      oldPrice: 18000,
      unitLabel: "por galon",
      minOrderLabel: "Min: 3 galones",
      stock: 200,
      badges: [
        { label: "-17%", tone: "sale" },
        { label: "Top ventas", tone: "hot" },
      ],
    },
    {
      id: "azucar-refinada-2-5kg",
      name: "Azucar Refinada 2.5kg",
      brand: "Dulce Colombia",
      category: "Alimentos",
      rating: 4.6,
      reviews: 175,
      price: 9800,
      unitLabel: "por paquete",
      minOrderLabel: "Min: 8 paquetes",
      stock: 320,
    },
    {
      id: "jabon-tocador-pack-12",
      name: "Jabon de Tocador Pack x12",
      brand: "Suave Care",
      category: "Cuidado Personal",
      rating: 4.4,
      reviews: 62,
      price: 24000,
      oldPrice: 28000,
      unitLabel: "por pack",
      minOrderLabel: "Min: 2 packs",
      stock: 75,
      badges: [
        { label: "-14%", tone: "sale" },
        { label: "Nuevo", tone: "new" },
      ],
    },
    {
      id: "leche-entera-uht-1l-x6",
      name: "Leche Entera UHT 1L x6",
      brand: "Lacteos del Valle",
      category: "Lacteos",
      rating: 4.7,
      reviews: 203,
      price: 18500,
      unitLabel: "por six-pack",
      minOrderLabel: "Min: 4 six-packs",
      stock: 180,
      badges: [{ label: "Top ventas", tone: "hot" }],
    },
    {
      id: "papel-higienico-24",
      name: "Papel Higienico x24 Rollos",
      brand: "SuaveMax",
      category: "Limpieza",
      rating: 4.5,
      reviews: 147,
      price: 32000,
      oldPrice: 36000,
      unitLabel: "por paquete",
      minOrderLabel: "Min: 2 paquetes",
      stock: 95,
      badges: [{ label: "-11%", tone: "sale" }],
    },
    {
      id: "cafe-molido-500g",
      name: "Cafe Molido Premium 500g",
      brand: "Montana Dorada",
      category: "Bebidas",
      rating: 4.9,
      reviews: 312,
      price: 28000,
      unitLabel: "por bolsa",
      minOrderLabel: "Min: 6 bolsas",
      stock: 120,
      badges: [{ label: "Top ventas", tone: "hot" }],
    },
  ],
}

export const CATALOG_SORT_OPTIONS = [
  "Mas populares",
  "Precio: menor a mayor",
  "Precio: mayor a menor",
  "Nuevos",
] as const

export const CATALOG_BADGE_STYLES = {
  sale: "bg-red-500 text-white",
  hot: "bg-orange-500 text-white",
  new: "bg-emerald-600 text-white",
} as const
